#   Commando
- type: job
  parent: CMJobBase
  id: RMCPMCCommandoXenospecialist
  name: rmc-job-name-pmc-commando-xenospecialist
  description: rmc-ghost-role-information-pmc-description
  playTimeTracker: RMCJobPMCCommandoXenospecialist
  ranks:
    RMCRankWeYaCommandoCatcher: []
  startingGear: RMCJobPMCCommandoXenospecialist
  icon: RMCJobIconPMCCommandoXenospecialist
  joinNotifyCrew: false
  accessGroups:
  - Colony
  - RMCWeYa
  spawnMenuRoleName: WEYA PMC Commando Xenospecialist
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WeYa
    - type: Skills
      skills:
        RMCSkillCqc: 3
        RMCSkillFirearms: 2
        RMCSkillPolice: 2
        RMCSkillFireman: 2
        RMCSkillConstruction: 2
        RMCSkillEngineer: 2
        RMCSkillSmartGun: 1
        RMCSkillEndurance: 3
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: rmc-job-prefix-pmc-commando-xenospecialist
  hidden: true

- type: entity
  id: RMCRandomHumanoidPMCCommandoXenospecialist
  name: weya pmc commando xenospecialist ghost role
  suffix: Spawner, Player
  components:
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: pmc_spawn
  - type: RandomHumanoidSpawner
    settings: RMCPMCCommandoXenospecialist

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointPMCCommandoXenospecialist
  name: weya pmc commando xenospecialist spawn point
  components:
  - type: SpawnPoint
    job_id: RMCPMCCommandoXenospecialist
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: pmc_spawn

- type: randomHumanoidSettings
  parent: EventHumanoid
  id: RMCPMCCommandoXenospecialist
  components:
  - type: GhostRole
    name: rmc-ghost-name-pmc-commando-xenospecialist
    description: rmc-ghost-role-information-pmc-description
    rules: rmc-ghost-role-information-pmc-rules
    reregister: false
    job: RMCPMCCommandoXenospecialist
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: CMJobRifleman
      time: 18000 # 5 Hours
  - type: GhostRoleApplySpecial
    squad: SquadPMC

- type: startingGear
  id: RMCJobPMCCommandoXenospecialist
  equipment:
    id: RMCIDCardPMC
    ears: RMCHeadsetDistressPMC
    jumpsuit: RMCJumpsuitVeteranPMCCommando
    outerClothing: CMArmorM4PMCCommando
    gloves: RMCHandsVeteranPMCCommando
    head: ArmorHelmetPMCCommando
    shoes: RMCBootsPMCCommandoFilled
    mask: RMCMaskBalaclava # TODO RMC14: M8 pattern armored balaclava
    suitstorage: RMCWeaponRifleM54C2
    pocket1: RMCPouchToolsCommandoFill
    pocket2: RMCPouchMedicalCommandoFill
    belt: RMCCommandoXenospecialistBeltFilled #TODO RMC14 add bic, keto, etc
    eyes: RMCGlassesMedicalHUDGlasses #TODO RMC14: Mark 4 Battle Medic
    back: RMCSatchelLightpack #TODO RMC14: Replace custom backpack
  storage:
    outerClothing:
    - CMMagazineRifleM54CAP
    - CMMagazineRifleM54CAP
    back:
    - CMStunbaton
    - RMCMotionDetector # TODO RMC14: Replace with corporate version (detects all non PMC)
    - RMCBoxHandcuffs
    - RMCRadioHandheldColonyOff
    - CMRollerBedSpawnFolded
    - RMCSynthResetKey
    - CMDefibrillator #TODO RMC14: Replace with advanced defib
    - CMAdvFirstAidKitFilled #TODO RMC14: Replace with elite field revival kit

- type: playTimeTracker
  id: RMCJobPMCCommandoXenospecialist

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconPMCCommandoXenospecialist
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: pmc_commando_xenospecialist
