#   Commando
- type: job
  parent: CMJobBase
  id: RMCPMCCommandoStandard
  name: rmc-job-name-pmc-commando-standard
  description: rmc-ghost-role-information-pmc-description
  playTimeTracker: RMCJobPMCCommandoStandard
  ranks:
    RMCRankWeYaCommando: []
  startingGear: RMCJobPMCCommandoStandard
  icon: RMCJobIconPMCCommandoStandard
  joinNotifyCrew: false
  accessGroups:
  - Colony
  - RMCWeYa
  spawnMenuRoleName: WEYA PMC Commando
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WeYa
    - type: Skills
      skills:
        RMCSkillCqc: 3
        RMCSkillFirearms: 3
        RMCSkillPolice: 2
        RMCSkillFireman: 3
        RMCSkillConstruction: 1
        RMCSkillEngineer: 1
        RMCSkillEndurance: 4
        RMCSkillMedical: 2
        RMCSkillSurgery: 2
        RMCSkillMeleeWeapons: 1
        RMCSkillJtac: 1
        RMCSkillVehicles: 1
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: rmc-job-prefix-pmc-commando-standard
  hidden: true

- type: entity
  id: RMCRandomHumanoidPMCCommandoStandard
  name: weya pmc commando ghost role
  suffix: Spawner, Player
  components:
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: pmc_spawn
  - type: RandomHumanoidSpawner
    settings: RMCPMCCommandoStandard

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointPMCCommandoStandard
  name: weya pmc commando spawn point
  components:
  - type: SpawnPoint
    job_id: RMCPMCCommandoStandard
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: pmc_spawn

- type: randomHumanoidSettings
  parent: EventHumanoid
  id: RMCPMCCommandoStandard
  components:
  - type: GhostRole
    name: rmc-ghost-name-pmc-commando-standard
    description: rmc-ghost-role-information-pmc-description
    rules: rmc-ghost-role-information-pmc-rules
    reregister: false
    job: RMCPMCCommandoStandard
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: CMJobRifleman
      time: 18000 # 5 Hours
  - type: GhostRoleApplySpecial
    squad: SquadPMC

- type: startingGear
  id: RMCJobPMCCommandoStandard
  equipment:
    id: RMCIDCardPMC
    ears: RMCHeadsetDistressPMC
    jumpsuit: RMCJumpsuitVeteranPMCCommando
    outerClothing: CMArmorM4PMCCommando
    gloves: RMCHandsVeteranPMCCommando
    head: ArmorHelmetPMCCommando
    shoes: RMCBootsPMCCommandoFilled
    mask: RMCMaskBalaclava # TODO RMC14: M8 pattern armored balaclava
    suitstorage: RMCWeaponRifleM54C2
    pocket1: RMCPouchToolsCommandoFill
    pocket2: RMCPouchMedicalCommandoFill
    belt: RMCCommandoBeltFilled
    eyes: RMCGlassesMedicalHUDGlasses #TODO RMC14: Mark 4 Battle Medic
    back: RMCSatchelLightpack #TODO RMC14: Replace with commando combat backpack
  storage:
    outerClothing:
    - RMCMagazineRifleM54CHEAP
    - RMCMagazineRifleM54CHEAP
    - RMCMagazineRifleM54CHEAP
    - RMCMagazineRifleM54CHEAP
    back:
    - CMStunbaton
    - RMCMotionDetector # TODO RMC14: Replace with corporate version (detects all non PMC)
    - RMCBoxHandcuffs
    - RMCRadioHandheldColonyOff
    - CMRollerBedSpawnFolded
    - RMCSynthResetKey
    - CMDefibrillator #TODO RMC14: Replace with advanced defib
    - CMAdvFirstAidKitFilled #TODO RMC14: Replace with elite field revival kit

- type: playTimeTracker
  id: RMCJobPMCCommandoStandard

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconPMCCommandoStandard
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: pmc_commando
