# Used in Shivas
- type: job
  parent: CMSurvivor
  id: RMCSurvivorCorporateCommando
  name: rmc-job-name-pmc-commando-standard
  description: rmc-ghost-role-information-pmc-description
  playTimeTracker: RMCJobSurvivorCorporateCommando
  ranks:
    RMCRankWeYaCommando: []
  startingGear: RMCJobSurvivorCorporateCommando
  icon: RMCJobIconSurvivorCorporateCommando
  joinNotifyCrew: false
  accessGroups:
  - Colony
  - RMCWeYa
  spawnMenuRoleName: WEYA PMC Commando (Shivas survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WeYa
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillFirearms: 2
        RMCSkillPolice: 2
        RMCSkillFireman: 2
        RMCSkillEngineer: 1
        RMCSkillEndurance: 2
        RMCSkillMedical: 2
        RMCSkillSurgery: 1
        RMCSkillMeleeWeapons: 1
        RMCSkillJtac: 1
        RMCSkillVehicles: 1
    - type: JobPrefix
      prefix: rmc-job-prefix-pmc-commando-standard
  hidden: true

- type: entity
  id: RMCRandomHumanoidSurvivorCorporateCommando
  name: weya pmc commando ghost role
  suffix: Spawner, Player
  components:
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: pmc_spawn
  - type: RandomHumanoidSpawner
    settings: RMCSurvivorCorporateCommando

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorCorporateCommando
  name: weya pmc commando spawn point
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorCorporateCommando
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    state: pmc_spawn

- type: randomHumanoidSettings
  parent: EventHumanoid
  id: RMCSurvivorCorporateCommando
  components:
  - type: GhostRole
    name: rmc-ghost-name-pmc-commando-standard
    description: rmc-ghost-role-information-pmc-description
    rules: rmc-ghost-role-information-pmc-rules
    reregister: false
    job: RMCSurvivorCorporateCommando
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: CMJobRifleman
      time: 18000 # 5 Hours
  - type: GhostRoleApplySpecial
    squad: SquadPMC

- type: startingGear
  id: RMCJobSurvivorCorporateCommando
  equipment:
    id: RMCIDCardPMC
    ears: RMCHeadsetDistressPMC
    jumpsuit: RMCJumpsuitVeteranPMCCommandoSurvivor
    outerClothing: CMArmorM4PMCCommando
    gloves: RMCHandsVeteranPMCCommando
    head: ArmorHelmetPMCCommando
    shoes: RMCBootsPMCCommandoFilled
    mask: RMCMaskBalaclava # TODO RMC14: M8 pattern armored balaclava
    suitstorage: RMCWeaponRifleM54CWhite
    pocket1: RMCPouchSurvivalBlackFilled
    pocket2: RMCPouchFirstAidPMCFill
    belt: RMCCommandoBeltFilled
    back: RMCSatchelLightpack #TODO RMC14: Replace with commando combat backpack
  storage:
    outerClothing:
    - CMMRE # TODO RMC14: PMC CFR ration
    back:
    - CMStunbaton
    - RMCZipties
    - RMCCigarettePackWeYaGold
    - RMCZippo
    - CMWEYAFlask
    #TODO RMC14: Elite field revival kit
    - CMDefibrillator

- type: playTimeTracker
  id: RMCJobSurvivorCorporateCommando

- type: jobIcon
  parent: CMJobIconBase
  id: RMCJobIconSurvivorCorporateCommando
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: pmc_commando
